# Generated by Django 5.1.2 on 2025-02-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_activity_end_time_alter_activity_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
    ]
