# Generated by Django 5.1.6 on 2025-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.CharField(max_length=200, verbose_name='活动描述'),
        ),
    ]
