# Generated by Django 5.1.2 on 2025-02-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField(max_length=200)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
            ],
        ),
    ]
