# Generated by Django 5.1.2 on 2025-02-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(max_length=200, verbose_name='活动描述'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=200, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.CharField(max_length=200, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.CharField(max_length=200, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=200, verbose_name='班级名称'),
        ),
    ]
