# Generated by Django 5.1.2 on 2025-02-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_school_class_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='owner',
        ),
    ]
