# Generated by Django 5.1.6 on 2025-02-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_activity_activity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='class',
            name='owner',
        ),
    ]
